### ISSUE TITLE
Flexible Content

### ISSUE THREAD

**Issue by elbotho** [clean-commit/gatsby-starter-henlo#11]
## Feature request

Add flexible content.

**What is the expected behavior?**
I just read your [article about flexible content](https://mrkaluzny.com/blog/acfs-flexible-content-with-gatsby-netlify-cms/) 👍. Then I came here hoping for a working example.

**How should this be implemented in your opinion?**
Just like described with one example component.

**Are you willing to work on this yourself?**
Sorry, no gatsby experience.

**Comment by mrkaluzny** [comment]
@elbotho I'm working on an upgraded version using `next` branch. The new starter will implement Page Builder as a backbone with more examples and documentation so stay tuned :)

**Comment by mrkaluzny** [comment]
@elbotho Just released v1 with remade flexible content sections :)
