### ISSUE TITLE
running a yarn build will result in two types of errors

### ISSUE THREAD

**Issue by GaryWenneker** [clean-commit/gatsby-starter-henlo#33]
# Bug report on Yarn Build

> https://www.gatsbyjs.com/docs/how-to/local-development/troubleshooting-common-errors/#field-image-must-not-have-a-selection-since-type-string-has-no-subfields

**What is the current behavior?**

running a yarn build will result in two types of errors:

- gatsby-remark-relative-images throws errors
- GraphQL query throws errors regarding types

![image](https://user-images.githubusercontent.com/6793205/215724167-eeec9ccb-664e-4ac3-9764-6439b7d21aab.png)

![image](https://user-images.githubusercontent.com/6793205/215724286-cde531df-5419-49a8-ac78-0b08304a7e78.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

- first way was to do a git clone of the master branch and run yarn to get the packages and then do a yarn build
- second way was to get the data doing the 'getting started way' doing a gatsby new [name] [repo]

**What is the expected behavior?**

No errors? ;-) (and maybe some way to thest and debug graphql ;-)

**Other relevant information:**

Node.js version:  v18.3.0
NPM/Yarn version: 8.11.0 / 1.22.15
Operating System:  Win11
Additional tools: Windows Terminal, VSCode

**Comment by GaryWenneker** [comment]
In netlify.toml I saw the usage of Yarn v. 1.9.4. so I installed npm 8.0.0. and 1.9.4. same messages :-(

**Comment by GaryWenneker** [comment]
Additional info, in the templates folder there are queries defined which use fragments. During the  yarn build these are not defined.
Adding them removes the error

![image](https://user-images.githubusercontent.com/6793205/215746411-82a4d950-2e81-43e5-a33a-377ddf97ad9b.png)

**Comment by mrkaluzny** [comment]
@GaryWenneker Thanks for the issue, I'll look into it next week :)

**Comment by gaerd** [comment]
any updates to this? I am really hyped on this starter but can't get it running locally. Deploys fine to Netlify though

 ERROR  UNKNOWN

Error loading a result for the page query in "index" / "/". Query was not run and no cached result was found. Couldn't get query results for "/" in 15.000s.

                                                                                                                                                                                                                                                                                   

  Error: Couldn't get query results for "/" in 15.000s.

  - get-page-data.ts:100
    [gatsby-starter-henlo]/[gatsby]/src/utils/get-page-data.ts:100:13

  - start-server.ts:320
    [gatsby-starter-henlo]/[gatsby]/src/utils/start-server.ts:320:24


                                                                                                                                                                                                                                                                                   
 ERROR #85922  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

      Field "ogimage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "ogimage". If you didn't expect "ogimage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "ogimage" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields.

File: src\components\Head\DefaultHead.js:122:15

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions


 ERROR #85922  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

      Field "image" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "image" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields.

File: src\components\PageBuilder.js:51:15

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions

                                                                                                                                                                                                                                                                                   
 ERROR #85922  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

      Field "thumbnail" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "thumbnail". If you didn't expect "thumbnail" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "thumbnail" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields.

File: src\hooks\useRecentArticles.js:24:27

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions

                                                                                                                                                                                                                                                                                   
 ERROR #85908  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

The fragment "Blocks" does not exist.

  23 | }
  24 |
  25 | export default Page
  26 |
  27 | export const Head = ({ data }) => (
  28 |   <DefaultHead data={data.page.frontmatter.seo}>
  29 |     <meta id="type" property="og:type" content="website" />
  30 |   </DefaultHead>
  31 | )
  32 |
> 33 | export const basicPageQuery = graphql`
     |                                       ^^^^^^^^^
  34 |   query BasicPage($id: String!) {
  35 |     page: markdownRemark(id: { eq: $id }) {
  36 |       id
  37 |       fields {
  38 |         slug
  39 |       }
  40 |       html
  41 |       frontmatter {
  42 |         id
  43 |         title

File: src\templates\page-builder.js

                                                                                                                                                                                                                                                                                   
 ERROR #85908  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

The fragment "Seo" does not exist.

  23 | }
  24 |
  25 | export default Page
  26 |
  27 | export const Head = ({ data }) => (
  28 |   <DefaultHead data={data.page.frontmatter.seo}>
  29 |     <meta id="type" property="og:type" content="website" />
  30 |   </DefaultHead>
  31 | )
  32 |
> 33 | export const basicPageQuery = graphql`
     |                                       ^^^^^^
  34 |   query BasicPage($id: String!) {
  35 |     page: markdownRemark(id: { eq: $id }) {
  36 |       id
  37 |       fields {
  38 |         slug
  39 |       }
  40 |       html
  41 |       frontmatter {
  42 |         id
  43 |         title

File: src\templates\page-builder.js


 ERROR #85908  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

The fragment "Seo" does not exist.

  31 |
  32 | export const Head = ({ data }) => (
  33 |   <DefaultHead data={data.post.frontmatter.seo}>
  34 |     {/* Additonal values here */}
  35 |     <meta id="oty" property="og:type" content="article" />
  36 |   </DefaultHead>
  37 | )
  38 |
  39 | export default Post
  40 |
> 41 | export const basicPageQuery = graphql`
     |                                       ^^^^^^
  42 |   query PostQuery($id: String!) {
  43 |     post: markdownRemark(id: { eq: $id }) {
  44 |       id
  45 |       html
  46 |       frontmatter {
  47 |         id
  48 |         title
  49 |         author
  50 |         ...Seo
  51 |       }

File: src\templates\post.js

failed extract queries from components - 0.109s                                                                                                                                                                                                                                    
success write out requires - 0.001s
success Writing page-data.json and slice-data.json files to public directory - 0.008s - 0/6 786.01/s

**Comment by mrkaluzny** [comment]
@gaerd @GaryWenneker Released new version, now both SEO and Photo fields have inferred type of File, this should solve the issues you were having.

Please let me know if you have any other issues :)
