### ISSUE TITLE
Feature Request: Would love to have it in TypeScript 

### ISSUE THREAD

**Issue by GaryWenneker** [clean-commit/gatsby-starter-henlo#34]
## Would love to have it in TypeScript 

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**
Intellisense

**How should this be implemented in your opinion?**
omitting Javascript and add TypeScript

**Are you willing to work on this yourself?**
YES

**Comment by mrkaluzny** [comment]
@GaryWenneker Yeah I would love to have it in TypeScript as well 😅

Definitely something we'll look into!

**Comment by mrkaluzny** [comment]
@GaryWenneker Are you still up to help us move this to TypeScript :)?
