### ISSUE TITLE
Forms missing

### ISSUE THREAD

**Issue by gaerd** [clean-commit/gatsby-starter-henlo#45]
# Bug report

**What is the current behavior?**
There is no form builder or form block in admin ui. Is there a roadmap or timeline for this feature?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Forms available as a collection and a form block in page builder

**Other relevant information:**
I've imported forms to cms.js and the form builder is now available.
Also added it to the blocks.map in PageBuilder.js so the block is available on pages.
I'm currently figuring out how to create the markup for the actual block to display it. 

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by mrkaluzny** [comment]
@gaerd I missed this completely, the CMS settings where there, I've added back the preview and all components necessary to get forms working

You can find them in latest [1.2.0 release](https://github.com/clean-commit/gatsby-starter-henlo/releases/tag/1.2.0)
